version: "3"

services:
  app:
    image: orcas:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ${ORCAS_WORKDIR}:/root
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
